### ISSUE TITLE
missing release tags

### ISSUE THREAD

**Issue by jrmarino** [AdaCore/e3-core#387]
It would be nice if version 22.0 was properly released as version v21.0.0 was (with a tag).

from NEWS.md:
Version 22.0.0 (2020-03-13)

This is very import to packages and used to repology.com to verify true releases and not just snapshots.
Obviously when 22.1.0 comes about, that should be tagged as well.  Whenever a commit is considered a release...

**Comment by jrmarino** [comment]
so I just noticed e3-core is on pypi, but that version is still 21.0.0.
So a second part of this issue is to update pypi concurrently with the release tags.

**Comment by enzbang** [comment]
Hi @jrmarino,

Thank you for reporting this issue.

Given that this release was dropping support for Python 2 we decided to slightly postpone the publication to pypi. I've now properly tagged the release and published it, see https://pypi.org/project/e3-core/22.0.0/
