### ISSUE TITLE
Use of the "source" string throughout the Anod class.

### ISSUE THREAD

**Issue by grouigrokon** [AdaCore/e3-core#614]
There are numerous tests in the `Anod` class (`e3/anod/spec.py`) which refer to a `"source"` string.

There is a `SOURCE_PRIMITIVE` (which could be defined out of the `TYPE_CHECKING`) which could be used.

The `Anod` class could define an `is_source` property like:

```python
@property
def is_source(self) -> bool:
    return self.kind == SOURCE_PRIMITIVE

```

**Comment by enzbang** [comment]
note that we should avoid having too many properties / methods in Anod given that this pollutes all specs

**Comment by grouigrokon** [comment]
You mean *inherit*  ;)
Five uses of `== "source"` in python files.
Two uses of `== "source"` in anod files.
No anod file defines `is_source`.
If you think this is not enough to create a property, I may close the bug.

**Comment by enzbang** [comment]
I think this is not enough to justify creating a property.
