### ISSUE TITLE
Add a new kind of qualifier: key_set qualifiers

### ISSUE THREAD

**Issue by JulienBortolussiAda** [AdaCore/e3-core#630]
Some qualifiers are actually expecting a list of value.

The current work around is to use key_value qualifier without choices and then to the parsing in the spec.

key_set qualifier will handle semi-column (";") separated list of values. The value will appears ordered in the build_space name.

**Comment by grouigrokon** [comment]
BTW, ";" is semi-column. "," is comma :)
